variables:
  REPO_NAME: gitlab.com/namespace/project

stages:
  - test
  - docker
  - deploy

test_app:
    before_script:
      - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
      - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
      - cd $GOPATH/src/$REPO_NAME
      - go get github.com/Masterminds/glide
      - glide install
    image: golang:latest
    stage: test
    script:
      - go test

build_image:
    image: docker:latest
    services:
      - docker:dind
    stage: docker
    script:
      - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" registry.gitlab.com
      - docker build -t registry.gitlab.com/etiennecoutaud1/go-demo .
      - docker push registry.gitlab.com/etiennecoutaud1/go-demo

deploy_fb:
  stage: deploy
  script:
    - echo "Deploy to CI_BUILD_REF_NAME server"
  environment:
    name: $CI_BUILD_REF_NAME
    url: https://CI_BUILD_REF_NAME.example.com
  only:
  - /^fb.*$

deploy_dev:
  stage: deploy
  script:
    - echo "Deploy to dev server"
  environment:
    name: dev
    url: https://dev.example.com
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to prod server"
  environment:
    name: prod
    url: https://prod.example.com
  only:
  - /^release.*$/
