# This file is a template, and might need editing before it works on your project.
image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/namespace/project

services:
- docker:dind

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go get github.com/Masterminds/glide
  - glide up

stages:
    - test
    - docker

test:
    stage: test
    script:
      - go test

compile:
    stage: docker
    script:
      - docker info
