FROM golang:1.16
WORKDIR /go/src/github.com/etiennecoutaud/go-demo
COPY . .
ENV GO111MODULE=off
RUN go get "github.com/google/uuid"
RUN go get "github.com/gorilla/mux"
RUN go get "github.com/prometheus/client_golang/prometheus/promhttp"
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s" -o go-demo

EXPOSE 8080
CMD ["/go-demo"]